SYSROOT=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.0.sdk

include ../theos/makefiles/common.mk

TOOL_NAME = afc2add
afc2add_FILES = afc2add.mm
afc2add_INSTALL_PATH = /

include $(FW_MAKEDIR)/tool.mk
