SYSROOT:=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk
include ../theos/makefiles/common.mk

TOOL_NAME = immutable
immutable_FILES = immutable.mm
immutable_INSTALL_PATH = /

include $(FW_MAKEDIR)/tool.mk
