SYSROOT:=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk

include ../theos/makefiles/common.mk

TOOL_NAME = sachet
sachet_FILES = sachet.mm
sachet_INSTALL_PATH = /

include $(FW_MAKEDIR)/tool.mk
