SYSROOT=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.0.sdk

include ../theos/makefiles/common.mk

TOOL_NAME = capable
capable_FILES = capable.mm
capable_INSTALL_PATH = /

include $(FW_MAKEDIR)/tool.mk
