GO_EASY_ON_ME=1
SYSROOT:=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk
include ../theos/makefiles/common.mk

TOOL_NAME = wuntar
wuntar_FILES = main.mm

include $(FW_MAKEDIR)/tool.mk