GO_EASY_ON_ME=1
SYSROOT:=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk
include ../theos/makefiles/common.mk

LIBRARY_NAME = hacktivate2
hacktivate2_C_FILES = hacktivate2.c

include $(THEOS_MAKE_PATH)/library.mk
